export const ACCESS_TOKEN = 'Access-Token'
export const SIDEBAR_TYPE = 'SIDEBAR_TYPE1'
export const DEFAULT_THEME = 'DEFAULT_THEME1'
export const DEFAULT_LAYOUT_MODE = 'DEFAULT_LAYOUT_MODE1'
export const DEFAULT_COLOR = 'DEFAULT_COLOR1'
export const DEFAULT_COLOR_WEAK = 'DEFAULT_COLOR_WEAK1'
export const DEFAULT_FIXED_HEADER = 'DEFAULT_FIXED_HEADER1'
export const DEFAULT_FIXED_SIDEMENU= 'DEFAULT_FIXED_SIDEMENU1'
export const DEFAULT_FIXED_HEADER_HIDDEN = 'DEFAULT_FIXED_HEADER_HIDDEN1'
export const DEFAULT_CONTENT_WIDTH_TYPE = 'DEFAULT_CONTENT_WIDTH_TYPE1'
export const DEFAULT_MULTI_PAGE = 'DEFAULT_MULTI_PAGE1'
export const USER_NAME = 'Login_Username'
export const USER_INFO = 'Login_Userinfo'
export const USER_AUTH = 'LOGIN_USER_BUTTON_AUTH'
export const SYS_BUTTON_AUTH = 'SYS_BUTTON_AUTH'
export const ENCRYPTED_STRING = 'ENCRYPTED_STRING'
export const DATA_SOURCE = 'DATA_SOURCE'
export const CHECK_SMS_DONLOAD = 'CHECK_SMS_DONLOAD'

export const CONTENT_WIDTH_TYPE = {
  Fluid: 'Fluid',
  Fixed: 'Fixed'
}